<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>il2cpp-inspect</AssemblyName>
    <RootNamespace>Il2CppInspector</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
    <MonoCecilPath Condition="'$(MonoCecilPath)'==''">$(HOME)/.local/share/Steam/steamapps/common/Among Us/BepInEx/core/Mono.Cecil.dll</MonoCecilPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil">
      <HintPath>$(MonoCecilPath)</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
